<%@ Page Language="C#" AutoEventWireup="true"  CodeBehind="Prodotti.aspx.cs" Inherits="ProvaDB.Prodotti" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <link href="stile.css" rel="stylesheet" />
    <!-- Collego La libreria JS per creare l'editor HTML -->
    <script src="https://cdn.ckeditor.com/4.15.1/standard/ckeditor.js"></script>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:SqlDataSource ID="dbc" runat="server"></asp:SqlDataSource>
            <!--
                 AutoGenerateColumns="false" -> Indica a .net di Usare le impostazioni di template invece di generare le colonne in autonomia
                 AutoGenerateSelectButton="false" -> Indica a .net di non generare i bottoni di select in autonomia
                 AutoGenerateDeleteButton="false" -> Indica a .net di non generare i bottoni in delete autonomia
            -->
            <!-- 
                Dentro Al TAG Columns
                Imposto i campi dati da mostrare 

                Imposto i Bottoni che mi servono 
                            CommandName="Select" -> Genera l'evento di Selezione
                            CommandName="Delete" -> Genera l'evento di Eliminazione
                            -->
            <asp:GridView ID="grdProdotti"
                DataKeyNames="Id"
                AutoGenerateSelectButton="false"
                AutoGenerateDeleteButton="false"
                AutoGenerateColumns="false"
                OnSelectedIndexChanged="grdProdotti_SelectedIndexChanged"
                OnRowDeleting="grdProdotti_RowDeleting"
                runat="server">

                <Columns>
                       <asp:BoundField DataField="Id" HeaderText="Id Prodotto" />
                       <asp:BoundField DataField="Nome" HeaderText="Nome Prod." />
                       <asp:TemplateField HeaderText="Immagine Prod.">
                           <ItemTemplate>                           
                               <asp:image runat="server" id="img1" width="150px" ImageUrl='<%# string.Concat("/Upload/",Eval("Immagine")) %>' ></asp:image>
                           </ItemTemplate>
                        </asp:TemplateField>
                       <asp:ButtonField ButtonType="Button" CommandName="Select" Text="Modifica" />
                       <asp:ButtonField ButtonType="Button" CommandName="Delete" Text="Cancella" />
                </Columns>

            </asp:GridView>



            <asp:FormView ID="frmProdotto" Visible="false" runat="server">
                <ItemTemplate>
                    <!--
                        I Tad <%# Eval("Id") %> servono per recuperare i valori dalla datasource e mostrarli nel punto
                        in cui sono posizionati
                        Per evitare problemi di Escape con le doppie virgolete
                        se i campi vengono associati ad una proprietà come ad esempio Text si si utilizzano gli apostrofi
                        come delimitatore di valore
                        Es.
                        Text='<%# Eval("Nome") %>'
                        -----^-------------------^ dove ci sono le frecciette non è possibile usare le virgolette
                    -->
                    <fieldset>
                        <legend>Modifica Prodotto  <%# Eval("Id") %> - <%# Eval("Nome") %> </legend>
                       
                        <div>
                            <label>Nome</label>
                            <asp:TextBox ID="txtNome" CssClass="colore" runat="server" Text='<%# Eval("Nome") %>'></asp:TextBox>
                        </div>
                        <div>
                            <label>Prezzo</label>
                            <asp:TextBox ID="txtPrezzo" runat="server" Text='<%# Eval("Prezzo") %>'></asp:TextBox>
                        </div>

                        <div>
                            <label>Descrizione</label>
                            <asp:TextBox ID="txtDescrizione" runat="server" Text='<%# Eval("Descrizione") %>'></asp:TextBox>
                            
                        </div>
                       
                        <div>
                            <label>Descrizione HTML</label>
                            <asp:TextBox ID="txtDescrizione_HTML" TextMode="MultiLine" runat="server" Text='<%# Eval("Descrizione_HTML") %>'></asp:TextBox>
                            <script>
                                //CKEDITOR.replace('frmProdotto_txtDescrizione_HTML');
                                //Collego CKEditor utilizzando ClientID
                                CKEDITOR.replace('<%= frmProdotto.FindControl("txtDescrizione_HTML").ClientID %>');
                            </script>
                        </div>

                        <div>
                            <label>Immagine</label>
                            <img src="/Upload/<%# Eval("Immagine") %>" style="max-width:250px" />
                            <br />
                            <!-- campo per Upload dei File -->
                            <asp:FileUpload ID="uplImmagine" runat="server" />
                        </div>

                        <div>
                            <label>Attivo</label>
                            <!-- Imposto la Proprietà SelectedValue con i dati provenienti dalla DataSource -->
                            <asp:DropDownList runat="server" SelectedValue='<%# Eval("Attivo") %>' ID="drpAttivo">
                                <asp:ListItem Value="S">Attivo</asp:ListItem>
                                <asp:ListItem Value="N">Non Attivo</asp:ListItem>
                            </asp:DropDownList>
                        </div>                         
                        <asp:Button ID="btnAggiorna" runat="server" OnClick="btnAggiorna_Click" Text="Aggiorna" />
                        <asp:Button ID="btnAnnulla" runat="server" OnClick="btnAnnulla_Click" Text="Annulla" />
                    </fieldset>
                </ItemTemplate>
            </asp:FormView>

        </div>
    </form>
</body>
</html>
